version: '3.3'

networks:
  spring-admin-network:
    external: true

services:
  badgify:
    build:
      context: .
      args:
        JAR_FILE: "./target/badgify-1.1.0.jar"
    image: badgify
    container_name: badgify
    ports:
      - "127.0.0.1:8081:8585"
    networks:
      - spring-admin-network
