version: '3.3'

services:
  badgify:
    build:
      context: .
      args:
        JAR_FILE: "./target/badgify-1.1.0.jar"
    image: badgify
    container_name: badgify
    ports:
      - "127.0.0.1:8081:8585"
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:latest"
    container_name: mongo_db
    volumes:
      - ./data:/var/lib/mongodb
    environment:
    MONGO_INITDB_ROOT_USERNAME: USERNAME
    MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    ports:
      - "27017:27017"
